server:
  port: 8001
  
spring:
  application:    name: user-provider
  datasource:                           #设置数据源信息
    type: com.alibaba.druid.pool.DruidDataSource  #设置数据库连接池的类型
    driver-class-name: org.gjt.mm.mysql.Driver  #设置数据库驱动
    url: jdbc:mysql://127.0.0.1:3306/user?characterEncoding=utf8&useSSL=true      #设置数据库的url
    username: root  #mysql数据库的用户名
    password: 1234  #mysql数据库的密码
    dbcp2:
      min-idle: 5     #设置最小连接数
      initial-size: 5 #设置当前数据连接池启东时，创建的连接数
      max-total: 10   #设置最大连接数据
      max-wait-millis: 2000   #设置最大等待时间
  jpa:                      #在控制台输出正确信息    show-sql: true
  mail:
    #设置SMYTP服务器    host: smtp.qq.com
    #设置发送方邮件
    username: 1466780176@qq.com
    #设置SMYTP服务密码（注意：不是登录密码！）
    password: xvejodsmutghjebd
    #设置字符集
    default-encoding: utf-8
    properties:       mail:
        smtp:
          auth: true
          ssl:
            enable: true    
     
eureka:  #启动eureka微服务url  client:    service-url:
      defaultZone: http://localhost:9000/eureka/
          
 